version: '3'
services:
  spring-boot-app:
    build:
      context: ./spring-boot/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  vue-app:
    build:
      context: ./vue/demo
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
